## This file install required R packages for the tutorials when the repo is first binderized
install.packages("readr")
install.packages("dplyr")
install.packages("plyr")
install.packages("magrittr")
install.packages("rmarkdown")        
install.packages("ggplot2")
install.packages("cowplot")
install.packages("caret")
install.packages("e1071")
install.packages("randomForest")
install.packages("earth")
install.packages("LiblineaR")
install.packages("kernlab")
